### ISSUE TITLE
Angular-strap issue

### ISSUE THREAD

**Issue by PhilBroadbent** [networknt/angular-schema-form-strapselect#3]
Hi - might not be an issue but I am stuck with it - simply trying to use a static multiselect however i'm getting the below. I don't even know why it's calling this (why does a dropdown use typahead?) 

My definition has:
        {
          fieldName: 'testmultiselect',
          title: 'Multi Select Static',
          type: 'array',
          format: 'strapselect',
          description: 'Multi single items are allowed',
          items: [
            {value: 'value1', label: 'label1'},
            {value: 'value2', label: 'label2'},
            {value: 'value3', label: 'long very very long label3'}
          ]
        }
(fieldname maps to "key" in form definition). so it's exactly the same, except schema definition also has this fieldName value but i don't see that throwing an error.

If I go into this function, attrs is undefined, as previous function tries to send attrs.bsOptions which doesn't exist.

2angular.js:11607 TypeError: Cannot read property 'match' of undefined
    at Object.angular.module.provider.$get.$parseOptions.init (http://localhost:9000/bower_components/angular-strap/dist/angular-strap.js:2344:46)
    at ParseOptionsFactory (http://localhost:9000/bower_components/angular-strap/dist/angular-strap.js:2379:23)
    at postLink (http://localhost:9000/bower_components/angular-strap/dist/angular-strap.js:3493:29)
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8219:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7729:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7078:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7081:13)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7724:24)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7078:13)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:6957:30) <button type="button" class="btn btn-default ng-pristine ng-untouched ng-valid" sf-changed="form" ng-model="model['testmultiselect']" schema-validate="form" data-placeholder="{{form.placeholder || form.schema.placeholder || ('placeholders.select' | translate)}}" data-multiple="1" data-html="1" ng-options="item.value as item.label for item in form.schema.items" bs-select="">angular.js:11607 (anonymous function)

Any help please?

**Comment by stevehu** [comment]
Yes. I know this problem and trying to make the demo works standalone. Basically the current code base only works within my own framework now. other people and myself is trying to make it work in the example. Thanks.

**Comment by PhilBroadbent** [comment]
Thanks for the quick response! Do you have any estimate about when this would be done? Thanks.

**Comment by stevehu** [comment]
In a couple of weeks I hope. And if you cannot wait, you can check out
light from my repo and there are three sites in it using strapselect and
uiselect (networknt, edibleforestgaden and example). Thanks.

**Comment by ruzz3ii** [comment]
An angular-strap issue is causing this. It works in angular-strap version 2.1.6.

https://github.com/mgcrea/angular-strap/issues/1587
https://github.com/mgcrea/angular-strap/issues/1606

**Comment by Elitward** [comment]
Hi,
Is this problem solved? I am using angular-strap @version v2.3.12 - 2017-01-26,
Original working code is broken for "Cannot read property 'match' of undefined" on <select ng-options ... >

**Comment by stevehu** [comment]
@PhilBroadbent I have switched from angular to react and my current job keeps busy all the time. Could you try to upgrade angular-strap and try it out?

**Comment by PhilBroadbent** [comment]
Hi - unfortunately I used this in a previous job and have since changed, so no longer use it. Would be quicker if @Elitward could try upgrade his codebase.

**Comment by Elitward** [comment]
@stevehu @PhilBroadbent  The issue has been solved. Some legacy code is using some class from boot-strap , I have updated it to use Angular-strap. Everything is working fine now. Sorry for the trouble.

**Comment by stevehu** [comment]
Thanks @Elitward for your confirmation.
